# Generated by Django 4.0.1 on 2022-01-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apphotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=250)),
                ('rua', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propriedade', models.CharField(choices=[('htl', 'Hotel'), ('psd', 'Pousada'), ('rst', 'Resort'), ('fzd', 'Fazenda')], max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nota_avaliacao', models.CharField(choices=[('b', 'Bom'), ('m', 'Médio'), ('r', 'Ruim')], max_length=1)),
                ('wifi', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=1)),
                ('tv', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=1)),
                ('camas', models.CharField(choices=[('1s', '1 Cama de Solteiro'), ('2s', '2 Camas de Solteiro'), ('1c', '1 Cama de Casal'), ('2c', '2 Camas de Casal'), ('3s', '1 Cama de Solteiro')], max_length=2)),
                ('descricao', models.CharField(blank=True, max_length=400, null=True)),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locador', to='apphotel.locador')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('quarto', models.ManyToManyField(to='apphotel.Local')),
            ],
        ),
        migrations.DeleteModel(
            name='Quartos',
        ),
    ]
