# Generated by Django 4.0.1 on 2022-01-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphotel', '0002_locador_local_reserva_delete_quartos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='camas',
            field=models.CharField(choices=[('1 Cama de Solteiro', '1 Cama de Solteiro'), ('2 Camas de Solteiro', '2 Camas de Solteiro'), ('1 Cama de Casal', '1 Cama de Casal'), ('2 Camas de Casal', '2 Camas de Casal'), ('3 Camas de Solteiro', '3 Camas de Solteiro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='local',
            name='nota_avaliacao',
            field=models.CharField(choices=[('Bom', 'Bom'), ('Médio', 'Médio'), ('Ruim', 'Ruim')], max_length=6),
        ),
        migrations.AlterField(
            model_name='local',
            name='propriedade',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Pousada', 'Pousada'), ('Resort', 'Resort'), ('Fazenda', 'Fazenda')], max_length=10),
        ),
        migrations.AlterField(
            model_name='local',
            name='tv',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='local',
            name='wifi',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3),
        ),
    ]
