# Generated by Django 4.0.1 on 2022-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphotel', '0003_alter_local_camas_alter_local_nota_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='nome_local',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='propriedade',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Pousada', 'Pousada'), ('Resort', 'Resort'), ('Fazenda', 'Fazenda')], max_length=7),
        ),
    ]
