# Generated by Django 4.0.1 on 2022-01-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apphotel', '0004_local_nome_local_alter_local_propriedade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locador',
            old_name='rua',
            new_name='bairro',
        ),
    ]
